#!/usr/bin/env node
/* =========================================================================
   os-mirror.mjs — Team OS → Obsidian vault bridge.

   Pulls os_tasks + os_content + latest activity from the LIVE Supabase project
   (via the linked Supabase CLI — Management API, bypasses RLS, uses the CLI's
   own login) and writes a clean markdown mirror into the vault. Overwrite on
   every run. Honest empty states.

   The write goes through ~/.collectiv4/vault-write.sh (Obsidian-aware: writes
   through Obsidian's Local REST API when it's open — no buffer clobber — else
   an atomic disk write). This is the same rail every scheduled vault write uses.

   RE-RUN (one command):
     node /Users/pato/The-Collectiv4/scripts/os-mirror.mjs
   Later this becomes a nightly launchd job pointed at exactly that command.
   ========================================================================= */

import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

const REPO = '/Users/pato/The-Collectiv4' // supabase CLI is linked from here
const VAULT_REL = '10 — Task Board/Team OS Mirror.md'
const VAULT_WRITE = '/Users/pato/.collectiv4/vault-write.sh'

const COLUMN_LABEL = { ideas: 'Ideas', this_week: 'This Week', in_motion: 'In Motion', done: 'Done' }
const COLUMN_ORDER = ['ideas', 'this_week', 'in_motion', 'done']

function query(sql) {
  try {
    const out = execFileSync('supabase', ['db', 'query', '--linked', sql], {
      cwd: REPO, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'], maxBuffer: 20 * 1024 * 1024,
    })
    const i = out.indexOf('{')
    if (i < 0) return []
    const parsed = JSON.parse(out.slice(i))
    if (!parsed.rows) { console.error('query returned no rows:', out.slice(0, 200)); return [] }
    return parsed.rows
  } catch (e) {
    console.error('query failed:', e.message)
    return []
  }
}

const pad2 = (n) => String(n).padStart(2, '0')
function today() {
  const d = new Date()
  return `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}`
}
const fmtDate = (s) => (s ? String(s).slice(0, 10) : '')
const relDay = (iso) => (iso ? String(iso).slice(0, 10) : '')

function main() {
  const profiles = query('select id::text as id, coalesce(full_name, username, \'—\') as name from public.profiles;')
  const nameById = {}
  profiles.forEach((p) => { nameById[p.id] = p.name })

  const tasks = query("select title, coalesce(type,'') as type, board_column, due_date::text as due_date, owner_profile_id::text as owner, created_at from public.os_tasks order by created_at;")
  const content = query("select title, coalesce(format,'') as format, coalesce(concept,'') as concept, coalesce(caption,'') as caption, status, planned_date::text as planned_date, owner_profile_id::text as owner from public.os_content order by created_at;")
  const activity = query("select action, created_at, profile_id::text as pid from public.os_activity order by created_at desc limit 30;")

  const lines = []
  lines.push('---')
  lines.push('type: os-mirror')
  lines.push(`date: ${today()}`)
  lines.push('area: Task Board')
  lines.push('---')
  lines.push('')
  lines.push('# Team OS — Mirror')
  lines.push('')
  lines.push('> Read-only snapshot of the internal Team OS (the `/os` hub in the platform). Regenerated by `scripts/os-mirror.mjs`. The live source of truth is the app — edit there, not here.')
  lines.push('')
  lines.push(`**Synced:** ${today()} · **${tasks.length}** tasks · **${content.length}** content pieces`)
  lines.push('')

  // BOARD
  lines.push('## Board')
  lines.push('')
  for (const col of COLUMN_ORDER) {
    const items = tasks.filter((t) => t.board_column === col)
    lines.push(`### ${COLUMN_LABEL[col]} (${items.length})`)
    if (!items.length) { lines.push('- — none —'); lines.push(''); continue }
    for (const t of items) {
      const bits = []
      if (t.type) bits.push(t.type)
      if (t.due_date) bits.push(`due ${fmtDate(t.due_date)}`)
      const owner = nameById[t.owner] || 'Unassigned'
      bits.push(owner)
      lines.push(`- **${t.title}** — ${bits.join(' · ')}`)
    }
    lines.push('')
  }

  // CONTENT
  lines.push('## Content Engine')
  lines.push('')
  if (!content.length) {
    lines.push('- — none —')
    lines.push('')
  } else {
    for (const c of content) {
      const meta = [c.format || 'format?', c.status]
      if (c.planned_date) meta.push(fmtDate(c.planned_date))
      meta.push(nameById[c.owner] || 'Unassigned')
      lines.push(`- **${c.title}** — ${meta.join(' · ')}`)
      if (c.concept) lines.push(`  - ${c.concept}`)
      if (c.caption) lines.push(`  - _caption:_ ${c.caption.replace(/\n+/g, ' ')}`)
    }
    lines.push('')
  }

  // ACTIVITY
  lines.push('## Signal — recent activity')
  lines.push('')
  if (!activity.length) {
    lines.push('- — none —')
  } else {
    for (const a of activity) {
      const who = nameById[a.pid] || 'Someone'
      lines.push(`- **${who}** ${a.action} · ${relDay(a.created_at)}`)
    }
  }
  lines.push('')
  lines.push(`*— mirror generated ${today()} by os-mirror.mjs.*`)
  lines.push('')

  const md = lines.join('\n')
  const tmp = join(tmpdir(), `os-mirror-${process.pid}.md`)
  writeFileSync(tmp, md, 'utf8')

  const result = execFileSync(VAULT_WRITE, [VAULT_REL, tmp], { encoding: 'utf8' }).trim()
  console.log(`Team OS Mirror written (${result}): ${tasks.length} tasks, ${content.length} content, ${activity.length} activity.`)
}

main()
